"""Optional RDKit geometry setup helpers."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from qchem_workbench.core.geometry import Atom, MoleculeGeometry, geometry_to_xyz_string


class RDKitUnavailableError(RuntimeError):
    """Raised when an RDKit helper is used without RDKit installed."""


def generate_conformer_xyz_files(
    smiles: str,
    molecule_name: str,
    output_dir: Path,
    number_of_conformers: int,
) -> dict[str, Any]:
    if number_of_conformers <= 0:
        raise ValueError("number_of_conformers must be positive")
    if not molecule_name.strip():
        raise ValueError("molecule_name cannot be empty")

    chem, all_chem = _load_rdkit()
    molecule = chem.MolFromSmiles(smiles)
    if molecule is None:
        raise ValueError(f"RDKit could not parse SMILES {smiles!r}")
    molecule = chem.AddHs(molecule)

    params = all_chem.ETKDGv3()
    params.randomSeed = 61453
    params.pruneRmsThresh = -1.0
    conformer_ids = list(
        all_chem.EmbedMultipleConfs(
            molecule, numConfs=number_of_conformers, params=params
        )
    )
    if not conformer_ids:
        raise ValueError("RDKit did not generate any conformers")

    target_dir = Path(output_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    safe_name = _safe_filename(molecule_name)
    conformers: list[dict[str, Any]] = []
    for index, conformer_id in enumerate(conformer_ids, start=1):
        conformer_label = f"conf_{index:03d}"
        geometry_path = target_dir / f"{safe_name}_{conformer_label}.xyz"
        geometry_path.write_text(
            geometry_to_xyz_string(
                _geometry_from_rdkit_conformer(
                    molecule,
                    int(conformer_id),
                    (
                        f"RDKit-generated starting conformer {conformer_label} for "
                        f"{molecule_name}; not a quantum-chemical minimum"
                    ),
                )
            ),
            encoding="utf-8",
        )
        conformers.append(
            {
                "id": conformer_label,
                "geometry_path": geometry_path.name,
                "rdkit_conformer_id": int(conformer_id),
            }
        )

    metadata = {
        "schema_version": 1,
        "generator": "rdkit",
        "smiles": smiles,
        "molecule_name": molecule_name,
        "number_requested": number_of_conformers,
        "number_generated": len(conformers),
        "conformers": conformers,
        "warnings": [
            "Generated by RDKit distance-geometry embedding; not an optimized "
            "quantum-chemical minimum."
        ],
    }
    metadata_path = target_dir / f"{safe_name}_conformers.json"
    metadata_path.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    metadata["metadata_path"] = str(metadata_path)
    return metadata


def _load_rdkit():
    try:
        from rdkit import Chem
        from rdkit.Chem import AllChem
    except ImportError as exc:
        raise RDKitUnavailableError(
            "RDKit is required for conformer generation; install the optional "
            "dependency with qchem-workbench[rdkit]."
        ) from exc
    return Chem, AllChem


def _geometry_from_rdkit_conformer(
    molecule, conformer_id: int, comment: str
) -> MoleculeGeometry:
    conformer = molecule.GetConformer(conformer_id)
    atoms: list[Atom] = []
    for atom in molecule.GetAtoms():
        position = conformer.GetAtomPosition(atom.GetIdx())
        atoms.append(
            Atom(
                symbol=atom.GetSymbol(),
                x=float(position.x),
                y=float(position.y),
                z=float(position.z),
            )
        )
    return MoleculeGeometry(atoms=tuple(atoms), comment=comment)


def _safe_filename(value: str) -> str:
    filename = re.sub(r"[^A-Za-z0-9._-]+", "_", value.strip()).strip("._")
    return filename or "molecule"
